CREATE TABLE books(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
author_id INT NOT NULL);

CREATE TABLE authors(
id NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50)
);

ALTER TABLE authors 
ADD FOREIGN KEY (id) REFERENCES books(author_id);